name: 'Deployment'

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'public/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - run: npm install
      - name: Build
        run: |
          npm run-script build
          tar zcvf dist.tar.gz dist
      - name: Upload
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: 'dist.tar.gz'
          target: '/var/www/portfolio'
      - name: Update files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /var/www/portfolio
            rm -rf html
            tar zxvf dist.tar.gz
            mv dist html
            rm -rf dist.tar.gz
